#!/bin/bash

# This file was generated by Rigel.

cd ~/ros_workspace/
source /opt/ros/humble/setup.bash
source ./install/setup.bash
source ./.venv/bin/activate
PROBE_PATH="$(find /home/rigeluser/ros_workspace/src -maxdepth 3 -name readiness_probe.sh | head -n 1)"
if [ -z "$PROBE_PATH" ]; then echo "ERROR: readiness_probe.sh not found in workspace"; exit 1; fi
sudo install -m 0755 "$PROBE_PATH" /usr/local/bin/readiness_probe.sh
printenv

exec "${@:1}"